#include "wrapper.h"

WRAP_FUNC(exp)
WRAP_FUNC(cos)
WRAP_FUNC(sin)
WRAP_FUNC(tan)
WRAP_FUNC(pow)
WRAP_FUNC(expf)
WRAP_FUNC(sinf)
WRAP_FUNC(cosf)
WRAP_FUNC(tanf)
WRAP_FUNC(asin)
WRAP_FUNC(acos)
WRAP_FUNC(asinf)
WRAP_FUNC(atanf)
WRAP_FUNC(atan2f)
WRAP_FUNC(atan2)
WRAP_FUNC(sqrt)
WRAP_FUNC(sqrtf)
WRAP_FUNC(fmod)
WRAP_FUNC(modff)
WRAP_FUNC(ceil)
WRAP_FUNC(sincos)