#include "wrapper.h"

extern "C" {
    WRAP_FUNC_VOID(_ZNSt13runtime_errorD1Ev)
    WRAP_FUNC_VOID(_ZNSt13runtime_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE)
    WRAP_FUNC_VOID(_ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_)
    WRAP_FUNC(_ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base)
    WRAP_FUNC(_ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base)
    WRAP_FUNC_VOID(_ZNSt8__detail15_List_node_base7_M_hookEPS0_)
    WRAP_FUNC(_ZNKSt9basic_iosIcSt11char_traitsIcEE4failEv)
    WRAP_FUNC(_ZNKSt9basic_iosIcSt11char_traitsIcEE3eofEv)
    WRAP_FUNC(_ZNKSt9basic_iosIcSt11char_traitsIcEEntEv)
    WRAP_FUNC_VOID(_ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate)

    WRAP_FUNC(_ZNSt10filesystem7__cxx114path5_ListC1ERKS2_)
    WRAP_FUNC(_ZNKSt10filesystem7__cxx1118directory_iteratordeEv)
    WRAP_FUNC(_ZNSt12__shared_ptrINSt10filesystem7__cxx114_DirELN9__gnu_cxx12_Lock_policyE2EEC1Ev)
    WRAP_FUNC(_ZNSt10filesystem7__cxx1118directory_iteratorC1ERKNS0_4pathENS_17directory_optionsEPSt10error_code)
    WRAP_FUNC(_ZNSi4readEPcl)
    WRAP_FUNC(_ZNSo5writeEPKcl)

    WRAP_FUNC(_Znwm)
    WRAP_FUNC(_Znam)

    WRAP_FUNC_VOID(_ZdaPv)
    WRAP_FUNC_VOID(_ZdlPv)
    WRAP_FUNC_VOID(_ZdlPvm)
    WRAP_FUNC_VOID(_ZdaPvm)

    WRAP_FUNC(_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc)
    WRAP_FUNC(_ZNSolsEi)
    WRAP_FUNC(_ZNSolsEl)
    WRAP_FUNC(_ZNSolsEf)
    WRAP_FUNC(_ZNSolsEd)
    WRAP_FUNC(_ZNSolsEj)
    WRAP_FUNC(_ZNSolsEt)
    WRAP_FUNC(_ZNSolsEm)
    WRAP_FUNC(_ZNSolsEPFRSt8ios_baseS0_E)
    WRAP_FUNC(_ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_)
    WRAP_FUNC(_ZNSolsEPFRSoS_E)
    WRAP_FUNC(_ZNSirsERi)
    WRAP_FUNC(_ZNSirsERl)
    WRAP_FUNC(_ZNSirsERf)
    WRAP_FUNC(_ZNSirsERd)
    WRAP_FUNC(_ZNSirsERj)
    WRAP_FUNC(_ZNSirsERt)
    WRAP_FUNC(_ZNSirsERm)
    WRAP_FUNC(_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EE)
    WRAP_FUNC(_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4_)
    WRAP_FUNC(_ZNSt14basic_ofstreamIcSt11char_traitsIcEEC1ERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode)
    WRAP_FUNC(_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode)
    WRAP_FUNC_VOID(_ZNSt14basic_ifstreamIcSt11char_traitsIcEED1Ev)
    WRAP_FUNC(_ZNKSi6gcountEv)
    WRAP_FUNC_VOID(_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEED1Ev)
    WRAP_FUNC_VOID(_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode)
    WRAP_FUNC_VOID(_ZNSo5flushEv)

    WRAP_FUNC_VOID(_Unwind_Resume)
    WRAP_FUNC_VOID(__cxa_end_catch)
    WRAP_FUNC_VOID(__cxa_rethrow)
    WRAP_FUNC_VOID(__cxa_throw)
    WRAP_FUNC_VOID(__cxa_free_exception)
    WRAP_FUNC_VOID(__cxa_guard_abort)
    WRAP_FUNC_VOID(__cxa_guard_release)
    WRAP_FUNC_VOID(__cxa_throw_bad_array_new_length)
    WRAP_FUNC(__cxa_begin_catch)
    WRAP_FUNC(__cxa_allocate_exception)
    WRAP_FUNC(__cxa_guard_acquire)
    WRAP_FUNC(__cxa_atexit)
}
